---
title: "R Notebook"
output: html_notebook
---

```{r}
# setwd("C:/Users/leneo/Dropbox/Alene/Rscripts/Current")
# source("new_database/Reading.LMAS.Data.R")
# setwd("C:/Users/leneo/Dropbox/Alene/Rscripts/TP_Landuse")

rm(list=setdiff(ls(), c("newdata")))

```


```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(tidymodels)
library(ISLR)
library(rpart.plot)
library(vip)

df<-newdata %>% 
  filter(CHARACTERISTIC_NAME %in% c("PHOSPHORUS, TOTAL"),
         substr(SAMPLE_DATE,1,4)>'2010',
         INFORMATION_TYPE=="OW",
         !is.na(LAKE_HISTORY_ID)) %>% 
    filter(RSLT_VALIDATOR_QUALIFIER!="R"|is.na(RSLT_VALIDATOR_QUALIFIER)) %>% 
  mutate(RSLT_RESULT_VALUE=ifelse(!is.na(RSLT_VALIDATOR_QUALIFIER)&RSLT_VALIDATOR_QUALIFIER=="U",RSLT_METHOD_DETECTION_LIMIT/2,RSLT_RESULT_VALUE))%>%  
  filter(!is.na(RSLT_RESULT_VALUE))

depth<-df %>% select(LAKE_HISTORY_ID,CSLAPFD_SITE_SOUND_DEPTH,LCIFD_MAX_SOUND_DEPTH,RSLT_PROFILE_DEPTH,LCIFD_SITE_SOUND_DEPTH) %>% distinct() %>% 
  group_by(LAKE_HISTORY_ID) %>% 
  summarize(CSLAPFD_SITE_SOUND_DEPTH=max(CSLAPFD_SITE_SOUND_DEPTH,na.rm = TRUE),
            LCIFD_MAX_SOUND_DEPTH=max(LCIFD_MAX_SOUND_DEPTH,na.rm = TRUE),
            LCIFD_SITE_SOUND_DEPTH=max(LCIFD_SITE_SOUND_DEPTH,na.rm = TRUE),
            RSLT_PROFILE_DEPTH=max(RSLT_PROFILE_DEPTH,na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(depth=pmax(CSLAPFD_SITE_SOUND_DEPTH,LCIFD_MAX_SOUND_DEPTH,LCIFD_SITE_SOUND_DEPTH,RSLT_PROFILE_DEPTH,na.rm = TRUE)) %>% 
  select(LAKE_HISTORY_ID,depth) %>% 
  mutate(depth=as.numeric(depth)) %>% 
  filter(depth<500)

df<-merge(df,depth,by=c('LAKE_HISTORY_ID'),all=TRUE)

df<-df %>% 
  #convert to ppb
  mutate(phosphorus=1000*RSLT_RESULT_VALUE,
         depth=as.numeric(depth)) %>% 
  group_by(LAKE_HISTORY_ID) %>% 
  summarize(depth=max(depth),
         phosphorus=median(phosphorus)) %>% 
  ungroup()%>% 
  select(LAKE_HISTORY_ID,depth,phosphorus) %>% distinct() 

#add watershed disturbance
landcover_2016 <- read.csv("Statewide_Lake_Watershed_NLCD_2016_percentages_NHD_LakeID.csv")

landcover_2016<-landcover_2016 %>% 
  mutate(DEVELOPED=VALUE_21+VALUE_22+VALUE_23+VALUE_24,
         #note that the 2013 article did not use 81 (pasture hay) but we include it
         DISTURBANCE=VALUE_21+VALUE_22+VALUE_23+VALUE_24+VALUE_31+VALUE_82+VALUE_81) %>% 
  mutate(LAKE_HISTORY_ID = Lake_ID) %>% 
  filter(LAKE_HISTORY_ID!=" ") %>% 
  distinct(LAKE_HISTORY_ID,.keep_all = TRUE) %>% 
  select(LAKE_HISTORY_ID,DEVELOPED,DISTURBANCE,LkAcres) %>% distinct() 

TP_matrix<-inner_join(df, landcover_2016, by = "LAKE_HISTORY_ID")

#create category for size
#but only 2 under 2 acres
# TP_matrix<-TP_matrix %>%
#   #transform phosphorus to logtp
#   mutate(TP=log10(phosphorus)) %>%
#   select(LAKE_HISTORY_ID,TP,DISTURBANCE,depth,LkAcres) %>% distinct() %>%
#   mutate(DISTURBANCE = as.numeric(DISTURBANCE),
#          depth=as.numeric(depth),
#          depth=ifelse(depth==-Inf,NA,depth),
#          category=ifelse(LkAcres<2,"pond","lake")) %>%
#   filter(!is.na(TP),!is.na(DISTURBANCE),!is.na(LAKE_HISTORY_ID))


#create category for depth but there are many lakes without depth data
TP_matrix<-TP_matrix %>%
  #transform phosphorus to logtp
  mutate(TP=log10(phosphorus)) %>%
  select(LAKE_HISTORY_ID,TP,DISTURBANCE,depth,LkAcres) %>% distinct() %>%
  mutate(DISTURBANCE = as.numeric(DISTURBANCE),
         depth=as.numeric(depth),
         depth=ifelse(depth==-Inf,NA,depth),
         category=ifelse(!is.na(depth)&depth>2.1,"deep",ifelse(!is.na(depth),"shallow",NA))) %>%
  filter(!is.na(TP),!is.na(DISTURBANCE),!is.na(LAKE_HISTORY_ID))


#The red line uses the GAM functionality within ggplot2’s geom_smooth 
library(ggplot2)
print(plot<-ggplot(TP_matrix %>% filter(!is.na(category)))+
        geom_smooth(aes(x=DISTURBANCE,y=TP,fill=category))+
        geom_point(aes(x=DISTURBANCE,y=TP,color=category)))

#remove shallow lakes because the changepoint is more apparent
TP_matrix<-TP_matrix %>% 
  # filter(category=="deep") %>% distinct() %>% 
  select(LAKE_HISTORY_ID,TP,DISTURBANCE) %>% distinct()
TP_matrix<-as.data.frame(TP_matrix)

```

Removed the shallow lakes because the change point is more apparent in deep lakes

Landuse~TP
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}

h0<-NA
h1<-NA
TP<-TP_matrix[,2]
DISTURBANCE<-TP_matrix[,3]


cpdev2 <- rpart (TP ~ DISTURBANCE)             # This is the entire tree
cpdev1 <- snip.rpart(cpdev2,toss=2) # This trims one branch
cpdev <- snip.rpart(cpdev1, toss=3) # This has only the first split

rpart.plot(cpdev)  # This plots the first split, which is the changepoint.
cpdev

# The top number is the changepoint
# The bottom numbers are the averages of the response data to the left and the
# right of the changepoint.

### NOTE - Click on the graph, then select "Recording" from the "History"
# pull-down menu in the top left corner of the RGui window.  This will allow you
# to save graphs in memory.  Use the page up and page down buttons to cycle
# through the graphs in memory.


cpdev2 ### The entire tree based on RPART
rpart.plot(cpdev2)

z<- cpdev$splits[1,4]   # x value of changepoint
cpdev$frame
num<-cpdev$frame[1,2]
avg<-mean(DISTURBANCE)  # or cpdev$frame[1,5] will also get overall average
highx<-subset(TP_matrix, TP_matrix[,3]>z)
lowx<-subset(TP_matrix, TP_matrix[,3]<=z)
low<-mean(lowx[,3])
high<-mean(highx[,3])


out2<-c(z, low, high)
names(out2)<-c("chngp","mean left","mean right")
out2 ### This is the changepoint based on RPART

###########################################################################
###### Song Qian's (Duke Univeristy) code for computing changepoint with p-value
###### Song's code computes a slightly different changepoing.  I am not sure
###### if one is better than the other.
# 
#    mx <- sort(unique(DISTURBANCE))
#    m <- length(mx)
#    vi <- numeric()
#    vi [m] <- sum((TP - mean(TP))^2)
# 
#    for(i in 1:(m-1)) {
#       vi[i] <- sum((TP[DISTURBANCE <= mx[i]] - mean(TP[DISTURBANCE <=


#Plot with added changepoints
print(plot<-ggplot(TP_matrix,aes(x=DISTURBANCE,y=TP-log10(1000*.02)))+
        geom_smooth()+
        geom_vline(xintercept=12)+
        # geom_vline(xintercept=47)+
        geom_hline(yintercept=0)+
        geom_point(aes(x=DISTURBANCE,y=TP-log10(1000*.02)))+
        ylab("log TP deviation from WQS 20 ug/L or 1.3 in log scale")+
        xlab("% DISTURBANCE"))
# print(plot<-ggplot(TP_matrix,aes(x=DISTURBANCE,y=TP))+
#         geom_smooth()+
#         geom_vline(xintercept=37)+
#         # geom_vline(xintercept=47)+
#         geom_hline(yintercept=20)+
#         geom_point(aes(x=DISTURBANCE,y=TP))+
#         ylab("TP deviation from WQS 20 ug/L ")+
#         xlab("% DISTURBANCE")+
#         ylim(0, 80))

```




